[project]
name = "functions"
version = "0.1.0"
requires-python = ">=3.10,<3.12"  # Firebase Functions support 3.10 and 3.11
dependencies = [
    "firebase-admin>=6.7.0",
    "firebase-functions>=0.1.2",
    "flask>=3.1.0",
]
