name: Lint PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  lint-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
            docs
            style
            refactor
            perf
            test
          requireScope: false
          subjectPattern: ^[A-Z].+$
          subjectPatternError: |
            The subject must start with a capital letter.
            Examples:
              ✅ feat: Add new deployment option
              ✅ fix(functions): Resolve authentication issue
              ❌ feat: add new deployment option
          wip: true
          validateSingleCommit: false
          validateSingleCommitMatchesPrTitle: false
